### ISSUE TITLE
GraalVM Regression

### ISSUE THREAD

**Issue by brucethemoose** [etil2jz/etil-minecraft-flags#8]
I noticed you switched to recommending Adoptium instead. If its because the current GraalVM release is buggy/erroring, I think I narrowed that down:

https://github.com/oracle/graal/issues/4772
https://github.com/oracle/graal/issues/4775

In a nutshell, you want to add the flags `-Dgraal.VectorizeSIMD=false -Dgraal.UsePriorityInlining=false`

But you mentioned a memory leak... could you elaborate on that some?

**Comment by etil2jz** [comment]
Memory leak I mentioned isn't related to Graal, I just met people using unknown or private Java distributions having memory leaks, while you can simply have the Adoptium one which is safe to use.

I'll add back Graal arguments in another section of the readme, explaining it better because a lot of people opened issues because they didn't read the whole thing and got errors.

**Comment by brucethemoose** [comment]
Oh yeah, anything private sounds fishy. I think the only "public" OpenJDK builds that provide any kind of gain are Intel's build for Clear Linux and Oracle's Graal CE/EE.

For what its worth, I'm compiling my own Graal arguments here: https://github.com/brucethemoose/Minecraft-Java-Performance-Flags, building on yours but also adding/removing stuff based on some bugs others ran into. For instance, `Dfile.encoding=UTF-8` seems to break older version of Minecraft, while these flags break ARM environments (like Altra servers and M1 macs): `-XX:+UseNewLongLShift -XX:+UseXMMForArrayCopy -XX:+UseXmmI2D -XX:+UseXmmI2F -XX:+UseXmmLoadAndClearUpper -XX:+UseXmmRegToRegMoveAll -XX:+UseNewLongLShift`
